version: '3.7'

services:

  identity.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6000:5432"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=51800
      - CONNECTIONSTRINGS__IDENTITY=Server=identity.db;Database=Identity;User ID=sa;Password=P4ssW0rd!
    ports:
      - "51798:80"
      - "51800:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  measures.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6001:5432"

  measures.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=63796
      - CONNECTIONSTRINGS__MEASURES=Server=measures.db;Database=Measures;MultipleActiveResultSets=true;User ID=sa;Password=P4ssW0rd!
    ports:
      - "63795:80"
      - "63796:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    

  patients.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6003:5432"

  patients.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=54003
      - CONNECTIONSTRINGS__PATIENTS=Server=patients.db;Database=Patients;MultipleActiveResultSets=true;User ID=sa;Password=P4ssW0rd!
    ports:
      - "54002:80"
      - "54003:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 

  documents.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6005:5432"

  documents.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=52003
      - CONNECTIONSTRINGS__DOCUMENTS=Server=documents.db;Database=Documents;User ID=sa;Password=P4ssW0rd!
    ports:
      - "52002:80"
      - "52003:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro