version: '3.7'

services:

  eventstore:
    image: eventstore/eventstore:release-4.1.2
    
  identity.db:
    image: microsoft/mssql-server-linux:2017-CU12
    environment:
      ACCEPT_EULA: Y
      TZ: Europe/Brussels
  patients.db:
    image: microsoft/mssql-server-linux:2017-CU12
    environment:
      ACCEPT_EULA: Y
      TZ: Europe/Brussels
  measures.db:
    image: microsoft/mssql-server-linux:2017-CU12
    environment:
      ACCEPT_EULA: Y
      TZ: Europe/Brussels
  documents.db:
    image: microsoft/mssql-server-linux:2017-CU12
    environment:
      ACCEPT_EULA: Y
      TZ: Europe/Brussels


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/services/identity/Identity.API/Dockerfile
    depends_on:
      - identity.db
      - eventstore

  patients.api:
    image: ${DOCKER_REGISTRY-}patientsapi
    build:
      context: .
      dockerfile: src/services/patients/Patients.API/Dockerfile
    depends_on:
      - identity.api
      - patients.db
      - eventstore

  measures.api:
    image: ${DOCKER_REGISTRY-}measuresapi
    build:
      context: .
      dockerfile: src/services/measures/Measures.API/Dockerfile
    depends_on:
      - identity.api
      - measures.db
      - eventstore
  
  documents.api:
    image: ${DOCKER_REGISTRY-}documentsapi
    build:
      context: .
      dockerfile: src/services/document/Documents.API/Dockerfile
    depends_on:
      - identity.api
      - documents.db
      - eventstore