version: '3.7'

services:

  eventstore:
    image: eventstore/eventstore:release-4.1.2
    
  identity.db:
    image: ${SQL_SERVER_IMG}
    environment:
      ACCEPT_EULA: Y
      TZ: ${TZ}
  measures.db:
    image: ${SQL_SERVER_IMG}
    environment:
      ACCEPT_EULA: Y
      TZ: ${TZ}


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/services/identity/Identity.API/Dockerfile
    depends_on:
      - identity.db
      - eventstore

  patients.api:
    image: ${DOCKER_REGISTRY-}patientsapi
    build:
      context: .
      dockerfile: src/services/Patients/Patients.API/Dockerfile
    depends_on:
      - identity.api
      - patients.db
      - eventstore

  measures.api:
    image: ${DOCKER_REGISTRY-}measuresapi
    build:
      context: .
      dockerfile: src/services/Measures/Measures.API/Dockerfile
    depends_on:
      - identity.api
      - measures.db
      - eventstore

  medeasy.spa:
    image: ${DOCKER_REGISTRY-}medeasyspa
    build:
      context: .
      dockerfile: src/clients/web/MedEasy.SPA/Dockerfile
    depends_on:
      - identity.api
      - measures.api
      - patients.api