version: '3.6'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  measures.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "80"

networks:
  default:
    external:
      name: nat

