version: '3.7'

services:
  identity.db:
    image: microsoft/mssql-server-windows-express
    environment: 
      sa_password: P4ss_Word!
      ACCEPT_EULA: Y
    ports:
      - "6000:1433"
  identity.api:
    image: ${DOCKER_REGISTRY}identityapi
    environment:
      - CONNECTIONSTRINGS__IDENTITY=Server=identity.db;Database=Identity;MultipleActiveResultSets=true;User ID=sa;Password=P4ss_Word!
    build:
      context: .
      dockerfile: src\services\identity\Identity.API\Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - identity.db  
  measures.db:
    image: microsoft/mssql-server-windows-express
    environment:
      sa_password: P4ss_Word!
      ACCEPT_EULA: Y
    ports:
      - "6001:1433"
  measures.api:
    image: ${DOCKER_REGISTRY}measuresapi
    environment:
      - CONNECTIONSTRINGS__MEASURES=Server=measures.db;Database=measures;MultipleActiveResultSets=true;User ID=sa;Password=P4ss_Word!
    build:
      context: .
      dockerfile: src\services\Measures\Measures.API\Dockerfile
    depends_on:
      - measures.db
      - identity.api
    ports:
      - "5001:80"