version: '3.7'

services:

  identity.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6000:5432"
    networks:
      - dbs

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__IDENTITY=Server=identity.db;Database=identity;User ID=postgres;Password=P4ssW0rd!
    networks: 
      - apis
      - dbs
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  measures.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6001:5432"
    networks:
      - dbs

  measures.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__MEASURES=Server=measures.db;Database=measures;User ID=postgres;Password=P4ssW0rd!
    networks: 
      - apis
      - dbs
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    
  patients.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6003:5432"
    networks:
      - dbs

  patients.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__PATIENTS=Server=patients.db;Database=patients;User ID=postgres;Password=P4ssW0rd!
    networks: 
      - apis
      - dbs
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 

  documents.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6005:5432"
    networks:
      - dbs

  documents.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__DOCUMENTS=Server=documents.db;Database=documents;User ID=postgres;Password=P4ssW0rd!
    networks: 
      - apis
      - dbs
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  agenda.db:
    environment: 
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6006:5432"
    networks:
      - dbs

  agenda.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__AGENDA=Server=agenda.db;Database=agenda;User ID=postgres;Password=P4ssW0rd!
    networks: 
      - apis
      - dbs
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  nginx:
    ports:
      - "8000:80"
    networks: 
      - apis
    volumes:
      - ${APPDATA}/nginx/conf.d:/etc/nginx/conf.d
      - ${APPDATA}/nginx/templates:/etc/nginx/templates
     
networks:
  apis:
    driver: bridge
  dbs:
    driver: bridge