version: '3.7'

services:

  identity.db:
    environment: 
      SA_PASSWORD: P4ssW0rd!
      ACCEPT_EULA: Y
      TZ: Europe/Brussels
    ports:
      - "6000:1433"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=51800
      - CONNECTIONSTRINGS__IDENTITY=Server=identity.db;Database=Identity;MultipleActiveResultSets=true;User ID=sa;Password=P4ssW0rd!
    ports:
      - "51798:80"
      - "51800:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  

  measures.db:
    environment: 
      SA_PASSWORD: P4ssW0rd!
    ports:
      - "6001:1433"

  measures.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=63796
      - CONNECTIONSTRINGS__MEASURES=Server=measures.db;Database=Measures;MultipleActiveResultSets=true;User ID=sa;Password=P4ssW0rd!
    ports:
      - "63795:80"
      - "63796:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    

  patients.db:
    environment: 
      SA_PASSWORD: P4ssW0rd!
      ACCEPT_EULA: Y
      TZ: Europe/Brussels
    ports:
      - "6003:1433"


  patients.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=54003
      - CONNECTIONSTRINGS__PATIENTS=Server=patients.db;Database=Patients;MultipleActiveResultSets=true;User ID=sa;Password=P4ssW0rd!
    ports:
      - "54002:80"
      - "54003:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 
      
  documents.db:
    environment: 
      SA_PASSWORD: P4ssW0rd!
      ACCEPT_EULA: Y
      TZ: Europe/Brussels
    ports:
      - "6004:1433"


  documents.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=54003
      - CONNECTIONSTRINGS__PATIENTS=Server=documents.db;Database=Documents;MultipleActiveResultSets=true;User ID=sa;Password=P4ssW0rd!
    ports:
      - "64002:80"
      - "64003:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro 