# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: medeasy

services:
- name: identity-api
  project: src/services/identity/Identity.API/Identity.API.csproj
- name: measures-api
  project: src/services/Measures/Measures.API/Measures.API.csproj
- name: patients-api
  project: src/services/Patients/Patients.API/Patients.API.csproj
- name: agenda-api
  project: src/services/agenda/Agenda.API/Agenda.API.csproj
- name: documents-api
  project: src/services/document/Documents.API/Documents.API.csproj
- name: identity-db
  image: postgres:12-alpine
  env:
  - POSTGRES_PASSWORD="pass@word1"
  - POSTGRES_USER="identity_api"
  - POSTGRES_DB="identity"
  bindings:
    - containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User ID=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
- name: measures-db
  image: postgres:12-alpine
  env:
  - POSTGRES_PASSWORD="pass@word1"
  - POSTGRES_USER="measures_api"
  - POSTGRES_DB="measures"
  bindings:
    - containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User ID=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
- name: documents-db
  image: postgres:12-alpine
  env:
  - POSTGRES_PASSWORD="pass@word1"
  - POSTGRES_USER="documents_api"
  - POSTGRES_DB="documents"
  bindings:
    - containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User ID=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
- name: patients-db
  image: postgres:12-alpine
  env:
  - POSTGRES_PASSWORD="pass@word1"
  - POSTGRES_USER="patients_api"
  - POSTGRES_DB="patients"
  bindings:
    - containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User ID=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
- name: agenda-db
  image: postgres:12-alpine
  env:
  - POSTGRES_PASSWORD="pass@word1"
  - POSTGRES_USER="agenda_api"
  - POSTGRES_DB="agenda"
  bindings:
    - containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User ID=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
- name: seq
  image: datalust/seq
  env:
    - name: "ACCEPT_EULA"
      value: "Y"
  bindings:
    - name: ui
      port: 55340
      protocol: http
      containerPort: 80
    - name: internal
      containerPort: 5341
      port : 55341