// <auto-generated />
using System;
using Measures.DataStores;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Measures.DataStores.Sqlite.Migrations
{
    [DbContext(typeof(MeasuresStore))]
    [Migration("20211226181011_RenamePatientEntityToSubject")]
    partial class RenamePatientEntityToSubject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Measures.Objects.BloodPressure", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfMeasure")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("DiastolicPressure")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("SystolicPressure")
                        .HasColumnType("REAL");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId", "DateOfMeasure");

                    b.HasIndex("Id");

                    b.ToTable("BloodPressure");
                });

            modelBuilder.Entity("Measures.Objects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Measures.Objects.Temperature", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfMeasure")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("SubjectId", "DateOfMeasure");

                    b.HasIndex("Id");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("Measures.Objects.BloodPressure", b =>
                {
                    b.HasOne("Measures.Objects.Subject", "Subject")
                        .WithMany("BloodPressures")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Measures.Objects.Temperature", b =>
                {
                    b.HasOne("Measures.Objects.Subject", "Subject")
                        .WithMany("Temperatures")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Measures.Objects.Subject", b =>
                {
                    b.Navigation("BloodPressures");

                    b.Navigation("Temperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
